export const SVMdata = [
  {
    klasifikasi: "SVM",
    aktualPositif: 73,
    aktualNegatif: 27,
  },
  {
    klasifikasi: "SVM",
    aktualPositif: 54,
    aktualNegatif: 24,
  },
  {
    klasifikasi: "SVM",
    aktualPositif: 61,
    aktualNegatif: 33,
  },
];

export const NaiveBayesData = [
  {
    klasifikasi: "NaiveBayes",
    aktualPositif: 73,
    aktualNegatif: 27,
  },
  {
    klasifikasi: "NaiveBayes",
    aktualPositif: 54,
    aktualNegatif: 24,
  },
  {
    klasifikasi: "NaiveBayes",
    aktualPositif: 61,
    aktualNegatif: 33,
  },
];
export const DataKlasifikasi = [
  {
    ulasan: "Ulasan",
    prediksi: "negatif",
    hasil: "negatif",
  }
] 

export const DataLatih = [
  {
    "Date": "4/11/2024 05:42",
    "Username": "STEVEN DC",
    "Rating": 1,
    "Review Text": "Customer servicenya lama merespon keluhan pelanggan",
    "cleaning": "Customer servicenya lama merespon keluhan pelanggan",
    "case_folding": "customer servicenya lama merespon keluhan pelanggan",
    "normalisasi": "customer servicenya lama merespon keluhan pelanggan",
    "tokenize": "['customer', 'servicenya', 'lama', 'merespon', 'keluhan', 'pelanggan']",
    "stopword removal": "['customer', 'servicenya', 'merespon', 'keluhan', 'pelanggan']",
    "stemming_data": "customer servicenya merespon keluh langgan",
    "sentimen": "negatif"
  },
  {
    "Date": "4/11/2024 05:24",
    "Username": "Ahmad anis",
    "Rating": 1,
    "Review Text": "Aplikasi gk jelas pusban chat robot .malez apk ngaco",
    "cleaning": "Aplikasi gk jelas pusban chat robot malez apk ngaco",
    "case_folding": "aplikasi gk jelas pusban chat robot malez apk ngaco",
    "normalisasi": "aplikasi tidak jelas pusban chat robot malas aplikasi mengaco",
    "tokenize": "['aplikasi', 'tidak', 'jelas', 'pusban', 'chat', 'robot', 'malas', 'aplikasi', 'mengaco']",
    "stopword removal": "['aplikasi', 'tidak', 'pusban', 'chat', 'robot', 'malas', 'aplikasi', 'mengaco']",
    "stemming_data": "aplikasi tidak pusban chat robot malas aplikasi aco",
    "sentimen": "negatif"
  },
  {
    "Date": "4/11/2024 04:31",
    "Username": "Ali Machrus",
    "Rating": 3,
    "Review Text": "Masukannya saat masukkan pin pembayaran harusnya sudah pake sidik jari, jangan tulis pin, di spbu banyak kamera, untuk kenyamanan dan keamanan pengguna",
    "cleaning": "Masukannya saat masukkan pin pembayaran harusnya sudah pake sidik jari jangan tulis pin di spbu banyak kamera untuk kenyamanan dan keamanan pengguna",
    "case_folding": "masukannya saat masukkan pin pembayaran harusnya sudah pake sidik jari jangan tulis pin di spbu banyak kamera untuk kenyamanan dan keamanan pengguna",
    "normalisasi": "masukannya saat masukkan pin pembayaran harusnya sudah pakai sidik jari jangan tulis pin di spbu banyak kamera untuk kenyamanan dan keamanan pengguna",
    "tokenize": "['masukannya', 'saat', 'masukkan', 'pin', 'pembayaran', 'harusnya', 'sudah', 'pakai', 'sidik', 'jari', 'jangan', 'tulis', 'pin', 'di', 'spbu', 'banyak', 'kamera', 'untuk', 'kenyamanan', 'dan', 'keamanan', 'pengguna']",
    "stopword removal": "['masukannya', 'masukkan', 'pin', 'pembayaran', 'pakai', 'sidik', 'jari', 'tulis', 'pin', 'spbu', 'kamera', 'kenyamanan', 'keamanan', 'pengguna']",
    "stemming_data": "masuk masuk pin bayar pakai sidik jari tulis pin spbu kamera nyaman aman guna",
    "sentimen": "negatif"
  },
  {
    "Date": "4/11/2024 02:14",
    "Username": "Adi Vanda",
    "Rating": 1,
    "Review Text": "Aplikasi sampah",
    "cleaning": "Aplikasi sampah",
    "case_folding": "aplikasi sampah",
    "normalisasi": "aplikasi sampah",
    "tokenize": "['aplikasi', 'sampah']",
    "stopword removal": "['aplikasi', 'sampah']",
    "stemming_data": "aplikasi sampah",
    "sentimen": "negatif"
  },
  {
    "Date": "4/11/2024 02:10",
    "Username": "Zaenal Abidin",
    "Rating": 1,
    "Review Text": "Sebaiknya tersedia fitur hapus Akun dan ganti nomor telepon sendiri, biar gak lama ngantri berjam-jam chat ke CS. Jadi saya malas menggunakan aplikasi ini lagi dan saya tidak akan menggunakan aplikasi ini lagi.",
    "cleaning": "Sebaiknya tersedia fitur hapus Akun dan ganti nomor telepon sendiri biar gak lama ngantri berjamjam chat ke CS Jadi saya malas menggunakan aplikasi ini lagi dan saya tidak akan menggunakan aplikasi ini lagi",
    "case_folding": "sebaiknya tersedia fitur hapus akun dan ganti nomor telepon sendiri biar gak lama ngantri berjamjam chat ke cs jadi saya malas menggunakan aplikasi ini lagi dan saya tidak akan menggunakan aplikasi ini lagi",
    "normalisasi": "sebaiknya tersedia fitur hapus akun dan mengganti nomor telepon sendiri biar tidak lama mengantri chat ke cs jadi saya malas menggunakan aplikasi ini lagi dan saya tidak akan menggunakan aplikasi ini lagi",
    "tokenize": "['sebaiknya', 'tersedia', 'fitur', 'hapus', 'akun', 'dan', 'mengganti', 'nomor', 'telepon', 'sendiri', 'biar', 'tidak', 'lama', 'mengantri', 'chat', 'ke', 'cs', 'jadi', 'saya', 'malas', 'menggunakan', 'aplikasi', 'ini', 'lagi', 'dan', 'saya', 'tidak', 'akan', 'menggunakan', 'aplikasi', 'ini', 'lagi']",
    "stopword removal": "['tersedia', 'fitur', 'hapus', 'akun', 'mengganti', 'nomor', 'telepon', 'biar', 'tidak', 'mengantri', 'chat', 'cs', 'malas', 'aplikasi', 'tidak', 'aplikasi']",
    "stemming_data": "sedia fitur hapus akun ganti nomor telepon biar tidak antri chat cs malas aplikasi tidak aplikasi",
    "sentimen": "negatif"
  },
  {
    "Date": "4/11/2024 00:39",
    "Username": "Putri Sulistian",
    "Rating": 1,
    "Review Text": "Baru kali ini kecewa setelah memakai aplikasi ini bertahun2..saya mentransfer 3 yang lalu dan pending saldo pun terpotong gakada solusi hubungi cs pun hanya template😥😥 Hati2 jika menggunakan aplikasi ini gays",
    "cleaning": "Baru kali ini kecewa setelah memakai aplikasi ini bertahunsaya mentransfer  yang lalu dan pending saldo pun terpotong gakada solusi hubungi cs pun hanya template Hati jika menggunakan aplikasi ini gays",
    "case_folding": "baru kali ini kecewa setelah memakai aplikasi ini bertahunsaya mentransfer  yang lalu dan pending saldo pun terpotong gakada solusi hubungi cs pun hanya template hati jika menggunakan aplikasi ini gays",
    "normalisasi": "baru kali ini kecewa setelah memakai aplikasi ini bertahunsaya mentransfer yang lalu dan pending saldo pun terpotong solusi hubungi cs pun hanya template hati jika menggunakan aplikasi ini gays",
    "tokenize": "['baru', 'kali', 'ini', 'kecewa', 'setelah', 'memakai', 'aplikasi', 'ini', 'bertahunsaya', 'mentransfer', 'yang', 'lalu', 'dan', 'pending', 'saldo', 'pun', 'terpotong', 'solusi', 'hubungi', 'cs', 'pun', 'hanya', 'template', 'hati', 'jika', 'menggunakan', 'aplikasi', 'ini', 'gays']",
    "stopword removal": "['kali', 'kecewa', 'memakai', 'aplikasi', 'bertahunsaya', 'mentransfer', 'pending', 'saldo', 'terpotong', 'solusi', 'hubungi', 'cs', 'template', 'hati', 'aplikasi', 'gays']",
    "stemming_data": "kali kecewa pakai aplikasi bertahunsaya transfer pending saldo potong solusi hubung cs template hati aplikasi gays",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 23:48",
    "Username": "Gerakan Milenial Pataba",
    "Rating": 5,
    "Review Text": "Mntap",
    "cleaning": "Mntap",
    "case_folding": "mntap",
    "normalisasi": "mantap",
    "tokenize": "['mantap']",
    "stopword removal": "['mantap']",
    "stemming_data": "mantap",
    "sentimen": "positif"
  },
  {
    "Date": "3/11/2024 15:49",
    "Username": "Pekanbaru Riau",
    "Rating": 5,
    "Review Text": "Klo ganti nmr bisa gk",
    "cleaning": "Klo ganti nmr bisa gk",
    "case_folding": "klo ganti nmr bisa gk",
    "normalisasi": "kalau mengganti nomor bisa tidak",
    "tokenize": "['kalau', 'mengganti', 'nomor', 'bisa', 'tidak']",
    "stopword removal": "['mengganti', 'nomor', 'tidak']",
    "stemming_data": "ganti nomor tidak",
    "sentimen": "positif"
  },
  {
    "Date": "3/11/2024 14:08",
    "Username": "Agi Hanafi",
    "Rating": 5,
    "Review Text": "sangat bagus",
    "cleaning": "sangat bagus",
    "case_folding": "sangat bagus",
    "normalisasi": "sangat bagus",
    "tokenize": "['sangat', 'bagus']",
    "stopword removal": "['bagus']",
    "stemming_data": "bagus",
    "sentimen": "positif"
  },
  {
    "Date": "3/11/2024 13:09",
    "Username": "Fariz Hasbullah",
    "Rating": 1,
    "Review Text": "Top up emoney 100k, ga bs diupdate alias ilang.. saldo jg udah kepotong dan ga balik",
    "cleaning": "Top up emoney k ga bs diupdate alias ilang saldo jg udah kepotong dan ga balik",
    "case_folding": "top up emoney k ga bs diupdate alias ilang saldo jg udah kepotong dan ga balik",
    "normalisasi": "top up emoney ke tidak bisa diupdate alias hilang saldo juga sudah kepotong dan tidak balik",
    "tokenize": "['top', 'up', 'emoney', 'ke', 'tidak', 'bisa', 'diupdate', 'alias', 'hilang', 'saldo', 'juga', 'sudah', 'kepotong', 'dan', 'tidak', 'balik']",
    "stopword removal": "['top', 'up', 'emoney', 'tidak', 'diupdate', 'alias', 'hilang', 'saldo', 'kepotong', 'tidak']",
    "stemming_data": "top up emoney tidak diupdate alias hilang saldo potong tidak",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 09:44",
    "Username": "Indah Sartika",
    "Rating": 1,
    "Review Text": "App yg bermasalah udah motong trx tapi hasilnya nihil,",
    "cleaning": "App yg bermasalah udah motong trx tapi hasilnya nihil",
    "case_folding": "app yg bermasalah udah motong trx tapi hasilnya nihil",
    "normalisasi": "aplikasi yang bermasalah sudah memotong trx tapi hasilnya nihil",
    "tokenize": "['aplikasi', 'yang', 'bermasalah', 'sudah', 'memotong', 'trx', 'tapi', 'hasilnya', 'nihil']",
    "stopword removal": "['aplikasi', 'bermasalah', 'memotong', 'trx', 'hasilnya', 'nihil']",
    "stemming_data": "aplikasi masalah potong trx hasil nihil",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 06:24",
    "Username": "muhlisin",
    "Rating": 5,
    "Review Text": "Susah kirim uang nya,dan tidak ada pemberitahuan sama sekali",
    "cleaning": "Susah kirim uang nyadan tidak ada pemberitahuan sama sekali",
    "case_folding": "susah kirim uang nyadan tidak ada pemberitahuan sama sekali",
    "normalisasi": "susah kirim uang nyadan tidak ada pemberitahuan sama sekali",
    "tokenize": "['susah', 'kirim', 'uang', 'nyadan', 'tidak', 'ada', 'pemberitahuan', 'sama', 'sekali']",
    "stopword removal": "['susah', 'kirim', 'uang', 'nyadan', 'tidak', 'pemberitahuan']",
    "stemming_data": "susah kirim uang nyadan tidak pemberitahuan",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 05:44",
    "Username": "Muhammad Riyadi",
    "Rating": 5,
    "Review Text": "Saya tidak bisa update aplikasi terbaru",
    "cleaning": "Saya tidak bisa update aplikasi terbaru",
    "case_folding": "saya tidak bisa update aplikasi terbaru",
    "normalisasi": "saya tidak bisa update aplikasi terbaru",
    "tokenize": "['saya', 'tidak', 'bisa', 'update', 'aplikasi', 'terbaru']",
    "stopword removal": "['tidak', 'update', 'aplikasi', 'terbaru']",
    "stemming_data": "tidak update aplikasi baru",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 05:35",
    "Username": "Herry efrizall Efrizall",
    "Rating": 5,
    "Review Text": "Jozz..",
    "cleaning": "Jozz",
    "case_folding": "jozz",
    "normalisasi": "jozz",
    "tokenize": "['jozz']",
    "stopword removal": "['jozz']",
    "stemming_data": "jozz",
    "sentimen": "positif"
  },
  {
    "Date": "3/11/2024 02:34",
    "Username": "Gogo Gainrianto",
    "Rating": 3,
    "Review Text": "Biaya admin dari link aj syariah ke bank lain 6k,wadaw mahal bnr",
    "cleaning": "Biaya admin dari link aj syariah ke bank lain kwadaw mahal bnr",
    "case_folding": "biaya admin dari link aj syariah ke bank lain kwadaw mahal bnr",
    "normalisasi": "biaya admin dari link saja syariah ke bank lain kwadaw mahal benar",
    "tokenize": "['biaya', 'admin', 'dari', 'link', 'saja', 'syariah', 'ke', 'bank', 'lain', 'kwadaw', 'mahal', 'benar']",
    "stopword removal": "['biaya', 'admin', 'link', 'syariah', 'bank', 'kwadaw', 'mahal']",
    "stemming_data": "biaya admin link syariah bank kwadaw mahal",
    "sentimen": "negatif"
  },
  {
    "Date": "3/11/2024 00:00",
    "Username": "Rahmat Lutfi",
    "Rating": 5,
    "Review Text": "Mau bayar apapun jadi lebih mudah",
    "cleaning": "Mau bayar apapun jadi lebih mudah",
    "case_folding": "mau bayar apapun jadi lebih mudah",
    "normalisasi": "mau bayar apapun jadi lebih mudah",
    "tokenize": "['mau', 'bayar', 'apapun', 'jadi', 'lebih', 'mudah']",
    "stopword removal": "['bayar', 'apapun', 'mudah']",
    "stemming_data": "bayar apa mudah",
    "sentimen": "positif"
  },
  {
    "Date": "2/11/2024 12:47",
    "Username": "agus wahyudi",
    "Rating": 5,
    "Review Text": "Link aja sering eror",
    "cleaning": "Link aja sering eror",
    "case_folding": "link aja sering eror",
    "normalisasi": "link saja sering eror",
    "tokenize": "['link', 'saja', 'sering', 'eror']",
    "stopword removal": "['link', 'eror']",
    "stemming_data": "link eror",
    "sentimen": "negatif"
  },
  {
    "Date": "2/11/2024 10:30",
    "Username": "Meggie Maulana",
    "Rating": 3,
    "Review Text": "Mau coba klu bagus tak ksih bntang 5.",
    "cleaning": "Mau coba klu bagus tak ksih bntang",
    "case_folding": "mau coba klu bagus tak ksih bntang",
    "normalisasi": "mau coba kalau bagus tidak kasih bintang",
    "tokenize": "['mau', 'coba', 'kalau', 'bagus', 'tidak', 'kasih', 'bintang']",
    "stopword removal": "['coba', 'bagus', 'tidak', 'kasih', 'bintang']",
    "stemming_data": "coba bagus tidak kasih bintang",
    "sentimen": "positif"
  },
  {
    "Date": "2/11/2024 09:58",
    "Username": "Gabriel Pratama Putra",
    "Rating": 1,
    "Review Text": "Upgrade ke premium lama",
    "cleaning": "Upgrade ke premium lama",
    "case_folding": "upgrade ke premium lama",
    "normalisasi": "upgrade ke premium lama",
    "tokenize": "['upgrade', 'ke', 'premium', 'lama']",
    "stopword removal": "['upgrade', 'premium']",
    "stemming_data": "upgrade premium",
    "sentimen": "negatif"
  },
  {
    "Date": "2/11/2024 09:17",
    "Username": "Chen Changan",
    "Rating": 3,
    "Review Text": "Kenapa saya nggak bisa untuk mengganti nomor hp lama saya yang sudah terblokir ke nomor baru ?",
    "cleaning": "Kenapa saya nggak bisa untuk mengganti nomor hp lama saya yang sudah terblokir ke nomor baru",
    "case_folding": "kenapa saya nggak bisa untuk mengganti nomor hp lama saya yang sudah terblokir ke nomor baru",
    "normalisasi": "kenapa saya tidak bisa untuk mengganti nomor hp lama saya yang sudah terblokir ke nomor baru",
    "tokenize": "['kenapa', 'saya', 'tidak', 'bisa', 'untuk', 'mengganti', 'nomor', 'hp', 'lama', 'saya', 'yang', 'sudah', 'terblokir', 'ke', 'nomor', 'baru']",
    "stopword removal": "['tidak', 'mengganti', 'nomor', 'hp', 'terblokir', 'nomor']",
    "stemming_data": "tidak ganti nomor hp blokir nomor",
    "sentimen": "positif"
  },
  {
    "Date": "2/11/2024 08:11",
    "Username": "Nafila Sevenfoldism",
    "Rating": 1,
    "Review Text": "Saya transaksi gagal tapi uang saya gak balik",
    "cleaning": "Saya transaksi gagal tapi uang saya gak balik",
    "case_folding": "saya transaksi gagal tapi uang saya gak balik",
    "normalisasi": "saya transaksi gagal tapi uang saya tidak balik",
    "tokenize": "['saya', 'transaksi', 'gagal', 'tapi', 'uang', 'saya', 'tidak', 'balik']",
    "stopword removal": "['transaksi', 'gagal', 'uang', 'tidak']",
    "stemming_data": "transaksi gagal uang tidak",
    "sentimen": "negatif"
  },
  {
    "Date": "2/11/2024 07:48",
    "Username": "danlop wara",
    "Rating": 5,
    "Review Text": "klo bisa kirim ke rekening bank dan isi dari rekening bank aku pasti pake lah",
    "cleaning": "klo bisa kirim ke rekening bank dan isi dari rekening bank aku pasti pake lah",
    "case_folding": "klo bisa kirim ke rekening bank dan isi dari rekening bank aku pasti pake lah",
    "normalisasi": "kalau bisa kirim ke rekening bank dan isi dari rekening bank aku pasti pakai lah",
    "tokenize": "['kalau', 'bisa', 'kirim', 'ke', 'rekening', 'bank', 'dan', 'isi', 'dari', 'rekening', 'bank', 'aku', 'pasti', 'pakai', 'lah']",
    "stopword removal": "['kirim', 'rekening', 'bank', 'isi', 'rekening', 'bank', 'pakai']",
    "stemming_data": "kirim rekening bank isi rekening bank pakai",
    "sentimen": "positif"
  },
  {
    "Date": "2/11/2024 06:00",
    "Username": "Rifky nanang Wahyudi",
    "Rating": 1,
    "Review Text": "Aplikasi sering keluar2 sendiri hp udah ram 6 .. aplikasi rusak",
    "cleaning": "Aplikasi sering keluar sendiri hp udah ram   aplikasi rusak",
    "case_folding": "aplikasi sering keluar sendiri hp udah ram   aplikasi rusak",
    "normalisasi": "aplikasi sering keluar sendiri hp sudah ram aplikasi rusak",
    "tokenize": "['aplikasi', 'sering', 'keluar', 'sendiri', 'hp', 'sudah', 'ram', 'aplikasi', 'rusak']",
    "stopword removal": "['aplikasi', 'hp', 'ram', 'aplikasi', 'rusak']",
    "stemming_data": "aplikasi hp ram aplikasi rusak",
    "sentimen": "negatif"
  },
]

export const sentimentData = [
  {
    waktu: "Thu Dec 09 03:37:21 +0000 2021",
    id: 1468786822247370754,
    username: "bakutgou",
    score: 4,
    content:
      "wts voucher gofood sisa yang disc fee k aja langsung wa  voucher gofood discount diskon pot",
  },
  {
    waktu: "Thu Dec 09 03:36:10 +0000 2021",
    id: 1468786524690870274,
    username: "busifess",
    score: 4,
    content: "ppp ada yang punya voucher gofood pot k minbel k ini ga ",
  },
  {
    waktu: "Thu Dec 09 03:35:59 +0000 2021",
    id: 1468786478557773825,
    username: "aleyagist",
    score: 4,
    content: "reescnance gofood aja",
  },
  {
    waktu: "Thu Dec 09 03:31:08 +0000 2021",
    id: 1468785258300514308,
    username: "rrapunsyel",
    score: 3,
    content:
      "akusayangjeje Aku gk paham gofood gk prnh pk go food gk prnh kirim an sm pcar",
  },
  {
    waktu: "Thu Dec 09 03:30:08 +0000 2021",
    id: 1468785004415049729,
    username: "tadzkiaaaftrh",
    score: 3,
    content:
      "Gw ngotak ngatik sopifood sama gofood sejam lebih dah nyari harga yg pas ga nemu2",
  },
  {
    waktu: "Thu Dec 09 03:30:08 +0000 2021",
    id: 1468785004335431682,
    username: "asteroidea",
    score: 4,
    content:
      "Voucher gofood  fee k Minbel k Udah gofood Kalo menunya blm fix skip dulu ",
  },
  {
    waktu: "Thu Dec 09 03:29:42 +0000 2021",
    id: 1468784896747261952,
    username: "yusvandika",
    score: 4,
    content: "yusvandika Krikiland ga level gofood",
  },
  {
    waktu: "Thu Dec 09 03:27:45 +0000 2021",
    id: 1468784405296472065,
    username: "Eno_Bening",
    score: 3,
    content:
      "selama ga butuh amat gausah beli, jangan buka tokopedia sama jangan buka gofood ",
  },
  {
    waktu: "Thu Dec 09 03:27:44 +0000 2021",
    id: 1468784402700247043,
    username: "yusvandika",
    score: 4,
    content: "ftmhin Order gofood ",
  },
  {
    waktu: "Thu Dec 09 03:27:26 +0000 2021",
    id: 1468784323423727619,
    username: "_halsuisseo",
    score: 3,
    content:
      "cutepows makasi piooo nya Allah langsung maw gofood racun sekali aku met mam juga kalo gituu  wkwk",
  },
  {
    waktu: "Thu Dec 09 03:26:52 +0000 2021",
    id: 1468784183581417472,
    username: "rreweI",
    score: 4,
    content: "need voucher gofood yg udah gofood",
  },
  {
    waktu: "Thu Dec 09 03:24:34 +0000 2021",
    id: 1468783602993274881,
    username: "okinawa",
    score: 4,
    content: "Cuman k anjayyy nasi ayam dua telor es teh thankyou gofood ",
  },
  {
    waktu: "Thu Dec 09 03:24:26 +0000 2021",
    id: 1468783569598234624,
    username: "cutepows",
    score: 4,
    content:
      "halsuisseo IHH KAK HAUN PENGENN met mamm kak aku mau gofood ah ngiler ",
  },
  {
    waktu: "Thu Dec 09 03:24:22 +0000 2021",
    id: 1468783553374658560,
    username: "kevinmvun",
    score: 4,
    content: "voucher gofood dong yang bisa cek price dulu ",
  },
  {
    waktu: "Thu Dec 09 03:23:57 +0000 2021",
    id: 1468783448454152201,
    username: "parkeajz",
    score: 4,
    content: "menangiisi Di gofood ada kaga",
  },
];